name: Testing the runner
on: 
  Workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    steps:
     - uses: actions/checkout@v3
    
     - name: check the runner is working
       run: echo "THe runner is working"
