name: Build and Deploy Java Application to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]  # Use the appropriate label for your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the JDK version

      - name: Build with Maven
        run: mvn clean package  # Build the application and create a WAR file

      - name: Deploy to Tomcat
        run: |
          # Stop Tomcat service (optional, if needed)
          net stop Tomcat9  # Replace with your Tomcat service name

          # Deploy WAR file to Tomcat
          copy target\myapp.war C:\path\to\tomcat\webapps\

          # Start Tomcat service
          net start Tomcat9  # Replace with your Tomc
