name: Build and Deploy Java Application to Tomcat

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: ${{ inputs.environmnet == Dev}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11

        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'  # Specify the JDK version

      - name: Build with new Maven

        run: mvn -B package --file pom.xml 
      - name: Creates stagin directory and copy .war
        run: |
         New-Item -ItemType Directory -Path staging -Force
         Copy-Item -Path target\*.war -Destination staging\

       
     
      

          
