name: Deploy to Windows Server

on:
 workflow_dispatch:  # Replace with your desired branch

jobs:
  deploy:
    runs-on: self-hosted  # Assumes self-hosted runner on Windows Server
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Login to Docker Hub (optional)
        #if: ${{ secrets.DOCKER_USERNAME }}  # Only if Docker Hub credentials are stored
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:${{ secrets.DOCKERHUB_IMAGE_TAG }}

      - name: Run the image (or deploy to service)
        run: |
          docker run -d ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:${{ secrets.DOCKERHUB_IMAGE_TAG }}
          # OR (if deploying to a service)
          # docker service create --name my-service ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:${{ secrets.DOCKERHUB_IMAGE_TAG }}
