name: Build and Deploy Java Application to Tomcat

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17

        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven'  # Specify the JDK version

      - name: Build with new Maven

        run: mvn -B package --file pom.xml 
      - name: Creates stagin directory and copy .war
        run: |
          mkdir staging
          cp target/*.war staging/# Build the application and create a WAR file

      

          
