name: docker image

on:
  workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-java@v4
     with:
      java-version: '17'
      distribution: 'temurin'
   - name: Build with Maven
     run: mvn -B package --file pom.xml
   - name: Create new directory
     run: mkdir staging && cp target/*.jar staging
   - name: publish artifacts
     uses: actions/upload-artifact@v3
     with:
      name: Package
      path: staging
   - name: Build & push Docker image
     uses: mr-smithers-excellent/docker-build-push@v4
     with:
        image: divyaprabhavathi1012/javacode
        file: ./DockerFile  # Path to your Dockerfile
        push: true
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


