name: encryptJSON file
on: workflow_dispatch
jobs:
  encrypt_json:
    runs-on: self-hosted
    environment:
      dev
    steps:
      - name: Download JSON file
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/DivyaPrabhavathi/Maven/main/NSI.json" -OutFile "NSI.json"
        shell: powershell

      - name: Assign values to JSON file
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ENV_NAME: ${{ secrets.ENV_NAME }}
        run: |
          # Read JSON file and convert to object
          $json = Get-Content NSI.json | ConvertFrom-Json

          # Modify JSON object properties using environment variables
          $json.Sphere.USERNAME = $env:DOCKER_USERNAME
          $json.Sphere.PASSWORD = $env:DOCKER_PASSWORD
          $json.Sphere.NAME = $env:ENV_NAME

          # Convert modified object back to JSON string
          $plainTextJson = $json | ConvertTo-Json

      - name: Generate encryption key
        run: |
          $key = [System.Convert]::ToBase64String((New-Object System.Security.Cryptography.RNGCryptoServiceProvider).GetBytes(32))
          $key | Out-File -FilePath "encryption_key.txt"
          Write-Output "Encryption key: $key"
        shell: powershell
 
      - name: Encrypt JSON File
        run: |
          $key = Get-Content -Path "encryption_key.txt"
          $jsonContent = Get-Content -Path "NSI.json" -Raw
          $keyBytes = [System.Convert]::FromBase64String($key)
          $aes = New-Object System.Security.Cryptography.AesManaged
          $aes.Key = $keyBytes
          $aes.GenerateIV()
          $iv = [System.Convert]::ToBase64String($aes.IV)
          $encryptor = $aes.CreateEncryptor()
          $jsonBytes = [System.Text.Encoding]::UTF8.GetBytes($jsonContent)
          $encryptedBytes = $encryptor.TransformFinalBlock($jsonBytes, 0, $jsonBytes.Length)
          $encryptedContent = [System.Convert]::ToBase64String($encryptedBytes)
          $iv | Out-File -FilePath "iv.txt"
          $encryptedContent | Out-File -FilePath "encrypted.json"
          Write-Output "Encrypted JSON file generated: your_encrypted.json"
        shell: powershell
 
      - name: Upload encrypted JSON file and keys
        uses: actions/upload-artifact@v2
        with:
          name: encrypted-files
          path: |
            encrypted.json
            encryption_key.txt
            iv.txt
