name: TakingKeyfromJson
 
on:
  workflow_dispatch:
   
 
jobs:
  update_json:
    runs-on: self-hosted
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: check the JQ version
        run: |
          $env:Path += ";C:\ProgramData\chocolatey\bin"
          jq --version
    

      
 
      
