name: JQ installation
 
on:
  workflow_dispatch:

jobs:
  update_json:
    runs-on: self-hosted
    
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install jq on Windows
        run: |
         Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile jq.exe
          Move-Item -Path jq.exe -Destination 'C:\Users\DevOps\jq\jq.exe'
         [Environment]::SetEnvironmentVariable('PATH', $Env:PATH + ';C:\Users\DevOps\jq', [System.EnvironmentVariableTarget]::Machine)
        shell: powershell
          
      
      - name: check jq version
        run: |
          jq --version
