name: Update JSON file with secrets and variables

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
    - name: Check if JSON file exists
      run: test -f /job_dependencies/nsivalue.json && echo "File exists" || echo "File not found"
    - name: Update JSON file with secrets
      run: |
        jq '.PASSWORD = "${{ secrets.DOCKER_USERNAME }}" | .USERNAME = "${{ secrets.DOCKER_PASSWORD }}"' ./job_dependencies/nsivalue.json > /tmp/updated_nsivalue.json && mv /tmp/updated_nsivalue.json ./job_dependencies/nsivalue.json
