name: JSON file

on: 
  workflow_dispatch:

jobs:
  download_json:
    runs-on: self-hosted  # Specify self-hosted runner

    steps:
      - name: Download JSON file
        run: curl -o https://raw.githubusercontent.com/DivyaPrabhavathi/Maven/main/job_dependencies/jsonvalue.json -o C:\Sphere

