name: JSON file

on: 
  workflow_dispatch:

jobs:
  download_json:
    runs-on: self-hosted  # Specify self-hosted runner

    steps:
      - name: Download JSON file
        run: wget -O  C:\Sphere\result.json https://raw.githubusercontent.com/DivyaPrabhavathi/Maven/main/job_dependencies/jsonvalue.json 

      - name: assign the value to the json file
        run: |
         # Read JSON file
          $jsonContent = Get-Content -Raw -Path .job_dependencies/jsonvalue.json | ConvertFrom-Json
          $secretOne = ${{ secrets.DOCKER_USERNAME }}
          $secretTwo = ${{ secrets.DOCKER_PASSWORD }}
          $jsonContent.secret1 = $secretOne
          $jsonContent.secret2 = $secretTwo
          $jsonContent | ConvertTo-Json | Set-Content -Path ./C:/Sphere/result.json -Force

