name: JSON file

on: 
  workflow_dispatch:

jobs:
  download_json:
    runs-on: self-hosted  # Specify self-hosted runner

    steps:
      - name: Download JSON file
        run: curl -L https://raw.githubusercontent.com/DivyaPrabhavathi/Maven/main/job_dependencies/jsonvalue.json -o path/to/download/file.json

