name: JSON file

on: 
  workflow_dispatch:

jobs:
  download_json:
    runs-on: self-hosted  # Specify self-hosted runner

    steps:
      - name: Download JSON file
        run: wget -O   https://raw.githubusercontent.com/DivyaPrabhavathi/Maven/main/job_dependencies/jsonvalue.json 

      - name: assign the value to the json file
        run: |
         # Read JSON file
          $jsonContent = Get-Content -Raw -Path  | ConvertFrom-Json
          $secret1 = ${{ secrets.DOCKER_USERNAME }}
          $secret2 = ${{ secrets.DOCKER_PASSWORD }}
          $jsonContent.secret1 = $secretOne
          $jsonContent.secret2 = $secretTwo
          $jsonContent | ConvertTo-Json | Set-Content  -Force

