name: JSON file

on: 
  workflow_dispatch:

jobs:
  download_json:
    runs-on: self-hosted  # Specify self-hosted runner

    steps:
      - name: Download JSON file
        run: |
         Invoke-WebRequest -Uri "https://raw.githubusercontent.com/DivyaPrabhavathi/Maven/main/NSI.json" -OutFile "NSI.json"
        shell: powershell

      - name: assign the value to the json file
        run: |
         # Read JSON file
          $jsonContent = Get-Content NSI.json -Raw | ConvertFrom-Json
          $Password = ${{ secrets.DOCKER_USERNAME }}
          $Username = ${{ secrets.DOCKER_PASSWORD }}
          $jsonContent.DOCKER_USERNAME = $Password
          $jsonContent.DOCKER_PASSWORD  = $Username
          $jsonContent | ConvertTo-Json | Set-Content -Path NSI.json -Force

