name: testingrunner Workflow
on: workflow_dispatch
jobs:
  runner_test:
    runs-on: ubuntu-latest
    steps:
      #- uses: action/checkout@v3
      - name: Checking the runner
        run: echo "The runner is working correctly"

  job2:
    runs-on: ubuntu-latest
    steps: 
      - name: Teams notification
        uses: neonidian/teams-notify-build-status@v3
        with:
        
