name: Extract Secrets from JSON
 
on: 
 workflow_dispatch:
 
jobs:
  extract-secrets:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Read JSON file
        id: read_json
        run: |
          secret1=$(jq -r '${{ secrets.DOCKER_USERNAME }}' jsonvalue.json)
          secret2=$(jq -r '${{ secrets.DOCKER_PASSWORD }}' jsonvalue.json)
 
          echo "::set-output name=secret1::$secret1"
          echo "::set-output name=secret2::$secret2"
 
      - name: Use extracted secrets
        run: |
          echo "Secret1: ${{ steps.read_json.outputs.secret1 }}"
          echo "Secret2: ${{ steps.read_json.outputs.secret2 }}"
          
        
