name: Update JSON with Secrets
 
on:
  workflow_dispatch: # or the branch you want this workflow to run on
 
jobs:
  update-json:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set secret values in JSON
        run: |
          # Read the current content of the JSON file
          json_content=$(cat job_dependencies/nsivalue.json)
          
          # Update the JSON file with the secret values
          updated_json=$(echo "$json_content" | jq \
            --arg PASSWORD "${{ secrets.DOCKER_USERNAME }}" \
            --arg USERNAME "${{ secrets.DOCKER_PASSWORD }}" \
            
            '.key1 = $PASSWORD | .key3 = $USERNAME')
 
          # Write the updated content back to the JSON file
          echo "$updated_json" > job_dependencies/nsivalue.json
 
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add path/to/your-file.json
          git commit -m "Update JSON with secret values"
          git pushname: JSON secret
 
