name: webhook
on:
  workflow_dispatch:
    

jobs:
  JSONvalue:
    name: Print event
    runs-on: ubuntu-latest
    outputs:
     resulting: ${{ steps.set-value.outputs.result }}
    steps:
      - name: checking the JSON value
        id: set-value
        working-directory: ./job_dependencies
        run: | 
          echo "result=`perl -pe 's/\s+//g' nsivalue.json`" >> $GITHUB_OUTPUT


  job2:
      runs-on: ubuntu-latest
      needs: JSONvalue
      continue-on-error: true
      strategy:
        matrix:
           results: ${{ fromJSON(needs.JSONvalue.outputs.resulting) }}
        fail-fast: false
     
      steps:
          - name: checkin ght evalue
            run: echo "$matrix.results"
  
      

    
   
        
